config/routes.rb
Morgan::Application.routes.draw do
  get "pages/index"

  root 'pages#blog'

  PagesController.action_methods.each do |action|
    get "/#{action}", to: "pages##{action}", as: "#{action}_pages"
  end

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def python
  end

  def ruby
  end

  def android
  end

  def comps
  end

  def blog
  end

  def me
  end

  def recipes
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Morgan</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
<script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>
</head>
<body>
<div class="container">
<div class="text-center">
<h1>MORGAN JONES</h1>
<p>A CA native living in MN. Computer science grad from Carleton working at Target. This is a little more about me and what I build.</p>
<a href="https://twitter.com/jmorganbjones"><i class="icon-twitter"></i></a>
<a href="http://www.pinterest.com/jmbmjones/me/"><i class="icon-pinterest"></i></a>
<a href="http://www.linkedin.com/in/jmbjones/"><i class="icon-linkedin"></i></a>
<a href="http://www.github.com/jmbjones/"><i class="icon-github"></i></a>

  <div class="navbar">
	<div class="navbar-inner">
	<div class="container">
	    <ul class="nav nav-justified">
	      <li><%= link_to "Home", blog_pages_path %></li>
	      <li><%= link_to "Python", python_pages_path  %></li>
              <li><%= link_to "Ruby", ruby_pages_path  %></li>
              <li><%= link_to "Projects", comps_pages_path %></li>
	      <li><%= link_to "Me", me_pages_path %></li>
	    </ul>
	</div>
	</div>
  </div>
</div>
</div>
<div is="side-content">
  <%= yield(:side_bar) %>
</div>


<%= yield %>
</body>
</html>

app/views/pages/android.html.erb
<div class="container">
  <div class="text-center">
  <h2>My adventures in Android Land</h2>
  </div>

</div>

app/views/pages/comps.html.erb
<div class="container">
<h3 class="text-center">Projects: Past, Present, and Future</h3>

  <div class="hero-unit">
    <h3 class="text-center">Past</h3>
    <div class="about">
	<h4>Senior Integrative Exercise aka Comps</h4>
	<p><a href="http://www.NorthfieldCarpool.com">NorthfieldCarpool.com</a></p>
	<p>Each major at Carleton has seniors do a Senior Integrative Exercise, colloquially known as comps. The Computer Science major has a group comps where student take a project description and with the help of an advisor work through two terms (10 weeks each) to deliver a product. My comps topic was to create a web and iPhone service to create carpools between Northfield and the Twin Cities, <a href="http://cs.carleton.edu/cs_comps/1213/carpool/index.php">full description here</a>.</p>
	<div class="text-center"><iframe src="http://prezi.com/embed/578532ec606f4c4153b056c893890ad8c99e4a17/?bgcolor=ffffff&amp;lock_to_path=0&amp;autoplay=0&amp;autohide_ctrls=0&amp;features=undefined&amp;disabled_features=undefined" width="550" height="400" frameBorder="0" webkitAllowFullScreen mozAllowFullscreen allowfullscreen></iframe></div>
    </div>
  </div>

  <div class="hero-unit">
    <h3 class="text-center">Present</h3>
	<h4>Integrated Network Apps</h4>
	  <p>I am working with a group from our Product Design and Development Team on new ideas around Smart Objects.</p>

	<h4>Square Cash for Google Glass</h4>
	  <p>Girls In Tech - MSP received a pair of Google Glass through the Explorer's program. I am working with a few of their members to create a Google Glass app that sends money through Square Cash.</p>

  </div>

  <div class="hero-unit">
    <h3 class="text-center">Future</h3>
	<h4>Recipe Comparison</h4>
<p>When I look for new recipes online I often find myself pulling up at least 2 or 3 versions. I might have

an independent blogger, trusty Cook’s Illustrated, and the often simplified Food Network version. This 

allows me to accomplish a number of things. I can pick and choose ingredients, one might call for skim 

milk and the other heavy cream, determine how quickly I can make the recipe, and what shortcuts are 

ok and what they all agree on. I was doing this exact activity one day when I got fed up and decided 

that I needed to throw a solution to this on my project list. Instead of having to switch between tabs or 

windows, I will build something that digests several recipes from different sites, which all have different 

formats, and shows you clearly what is the same and what is different.</p>

<p>This tool will show the recipes side by side in a consistent format. It will show the different ingredients 

that are called for and how much time each recipe estimates it will take. Eventually, I want to calculate 

nutritional information for each, even if a recipe doesn’t list it explicitly. </p>

<p>To build this I think I am going to try out Django. I have extensive experience in Python and am very 

familiar with the MVC design pattern, but have not explored this way to use Python to build websites. I 

think my previous experience with web design, Python, and MVC will allow me to get this going quickly 

once I have a spare moment to devote to it.</p>

	<h4>WFH App</h4>
<p>At a work event one day the challenge to come up with a service that uses multiple APIs was presented.

We first brainstormed what kinds of APIs are out there from Google Maps to Pinterest and so many 

more. Once our minds were churning out those ideas it was time to pluck out some of those APIs and 

come up with a new idea. My mind immediately went to a combination of Google Maps traffic abilities, 

Wunderground’s forecasting, and Outlook’s calendars. These three could create a powerful prediction 

engine to tell you when you should Work From Home. I make this decision all the time and it usually 

boils down to a couple of questions? How many meetings do I have? Are said meetings in person or 

online? How bad is the weather (in Minneapolis that means how much snow would I have to trudge 

through)? And then how bad the weather is then allows me to predict just how horrid traffic will be (the 

more snow the worse it gets). Most of my answers to these questions are often educated guesses, and I 

would love to have more concrete data to help make this decision.</p> 

<p>Let me describe in a little bit more detail what I am thinking. Users will be asked to set up one time. 

They will input their home address and work address. There will be an average commute time 

calculation and a user can input their willingness to deviate from that e.g. 25 minutes more is too long, 

15 is ok. The user will also give permissions to their work calendar and input a few preferences. These 

might include how many meetings a day is too many too miss. Is there a tag for a particular meeting you 

don’t want to miss e.g. statuses can’t be missed, but update meetings can. Additionally you can input 

your work from home preferences aka you always work from home on Fridays and don’t really like to 

work from home more than two days a week. There are a lot of options here and these are just the ones 

I thought of off the top of my head.</p> 

<p>Once all the settings and preferences are dealt with the need for user inputs drops drastically. Now the 

user can ask the app simple questions. Should I work from home today? What day should I work from 

home this week? Can I work from home this week? A small set of easily understood and consistent 

questions should be developed to give the user the answers they want quickly. Once the user asks a 

question the algorithm would then calculate a recommendation based on their calendar, commute, and 

preferences.</p> 

<p>Additional functionality could be to send an email to a preset list of people saying you will be working 

from home that day or a certain day that week. Or it could add online meetings to the ones on your 

calendar that don’t have them already on the day you want to work from home. There are a lot of 

options for this to facilitate the increasing practice of working remotely.</p> 

<p>From a technology stand point there are a lot of options as well. This could be run through all Google 

products, it could be connected to any calendar that a company uses or that you connect through your 

phone. Initially I want to build this out for iOS as I already have a project in flight in Android and like to 

spread my projects to keep my skills fresh. However, this would be great on any platform. I like the idea 

of having this as an app as most people keep their work calendars and emails on their phone. Personally

I know I check the weather in the morning on my phone, look at my calendar for the day there, and take 

a peek at my email before I head out the door. Since I am already doing all these things on my phone 

(or maybe eventually tablet) already it makes sense to use this platform to seamlessly integrate into 

peoples’ morning routines.</p>
  </div>
</div>

app/views/pages/me.html.erb
<div class="container">
<div class="text-center">
<h2>If you really want to know</h2>
</div>
    <div class="hero-unit">
    <div class="text-center"><h3>Experience</h3></div>
    <h4>Technology Leadership Program, Target Corp</h4>
    <p>Rotational program with 3 rotations of 5 months each.</p>
    <p>1st Rotation: Engineer with Enterprise Services Support for APIs. I successfully ran a monitoring overhaul to ensure API performance during peak holiday season. As a result Target had 33 million+ API transactions on Black Friday alone with excellent health.</p>
    <p>2nd Rotation: Business Analyst in Strategy & Innovation: Marketing & Loyalty. Ran a Technology Exploration exercise to develop a technology recommendation for a new Guest Interaction space. Was the point of contact for all 7 vendors.</p>
    <p>3rd Rotation: Working on accelerated programs that deal with security in Guest Payment Devices</p>
    <h4>LaunchBit</h4>
    <p>Created a bookmarklet, CurateHub, that queues articles for curated e-mail newsletters integrated with MailChimp API. Cut down users' time from 3 hours to 8 minutes to send a newsletter. Handled customer development interviews across 5 verticals. Marketed product using Facebook Ads, Google Ad Sense, and direct marketing buys in relevant blogs.</p>
    <h4>Computer Science Lab Assistant</h4>
    <p>Assisted students with Computer Science homework and programming questions</p>
    <h4 class="job">Data Analytics Intern</h4>
    <p>Automated the process of reverse geo-location by producing IP ranges associated with companies for customers to target with advertisements. The service had a 2011 revenue goal of $750,000. Used Python to maximize recall from Oracle SQL database and narrowed results to increase precision . Created documentation and GUI for the process of reverse geo-location and to collapse IP ranges.</p>
    <h4>Clare Booth Luce Research Scholar</h4>
    <p>Researched routing in social networks to see if users’ interests can determine short paths. Scrubbed a data set that contained 3.97 million users and 1.85 million interests from LiveJournal. Developed Python programs to find similarities between users.</p>
    <h4>Law Clerk</h4>
    <p>Handled incoming calls and prepared 6-page client background information packages for consultations. Prepared multiple pleadings and attended court hearings. Performed research projects, filed daily correspondence, and organized resources.</p>
    </div>

  <div class="hero-unit">
    <div class="text-center"><h3>Education</h3></div>
    <h4>Carleton College 2013</h4>
    <p>Bachelor of Arts in Computer Science</p>
    <p>GPA: 3.5, graduated cum laude</p>
    <p>Job relevant coursework</p>
	<ul>
	<li>Software Design</li>
	<li>Data Structures</li>
	<li>Data Mining</li>
	<li>Database Systems</li>
	<li>Programming Languages</li>
	<li>Algorithms</li>
	<li>Computer Organization & Architecture</li>
	<li>Life in the Age of Networks</li>
	<li>Mathematics of Computer Science</li>
	<li>Computability & Complexity</li>
	</ul>
    <p>Life Relevant Courses</p>
	<ul>
	<li>Midwest and the American Imagination</li>
	<li>Logic</li>
	<li>Principles of Sustainable design</li>
	<li>Visions of California</li>
	<li>Social Cognition</li>
	<li>Arts of Oral Presentation</li>
	<li>Rap & Religion: Rhymes about God</li>
	</ul>
    <h4>Castilleja School, Palo Alto, CA</h4>
    <p>GPA 3.8</p>
    <br>
    </div>

    <div class="hero-unit">
   <div class="text-center"> <h3>Leadership</h3></div>
    <h4>Culinary House Manager</h4>
	<p>Lived in Carleton College interest house for 2 years. Ran it my senior year, handling the budget, any residential life issues, and selecting residents through an application process. We hosted events for the school and had house dinners 5 nights a week.</p>
    <h4>Growing Up Healthy</h4>
	<p>I taught a basic computer skills class in Spanish for the Northfield community.</p>
    <h4>KRLX Radio IT Engineer</h4>
	<p>The studio needed to redo the website as it sat on a very outdated and unstable codebase. I used my knowledge to help the rest of the board select the best path for redoing the website</p>
    <h4>Volleyball</h4>
	<p>I was a captain and won a State Championship in high school. I played for two years at Carleton and then coached the men's club team for two as well.
    </div>
</div>

app/views/pages/recipes.html.erb
<div class="container">
<h3>Papa's Carbonara Recipe</h3>

  <div class="row hero-unit">
    <div class="span4">
	<ul>
	  <li>1 Package Sphagetti</li>
	  <li>1 tub parmesan grated</li>
	  <li>2 eggs</li>
	  <li>1/2 Bag frozen peas</li>
	  <li>1 package pre-cubed pancetta</li>
	  <li>Salt and Pepper</li>
	  <li>Olive Oil</li>
	</ul>
    </div>
    <div class="span8">
	<ol>
	 <li> Boil water for the sphagetti</li>
	 <li> Heat olive oil in saute pan</li>
	 <li> Add pancetta to pan and crisp it</li>
	 <li> Add peas to pan and cook until they are all heated through</li>
	 <li> Add eggs to tub of parmesan and mix</li>
	 <li> Cook spagehtii and then drain</li>
	<li> Add spaghetti to pan and mix with eggs and pancetta</li>
	<li> While the sphaghetti, pancetta, and peas are stil hot add the parmesan-egg mixture and toss until the egg cooks a little and it has been mixted throughly and it is silky</li>
      </ol>
    </div>
  </div>
</div>

app/views/pages/ruby.html.erb
<div class="container">
  <div class="text-center">
  <h2>A Crown of Ruby Gems</h2>
  </div>
    <div class="hero-unit">
      <h3>This Site</h3>
	<p>This website is a Ruby experiment. While I am currently just using Twitter Bootstrap I plan on using it to experiment with new design and technology ideas in the future.</p>
    </div>
     <div class="hero-unit">
     <h3>My Wedding Site</h3>
     <a href="http://mysterious-beach-8993.herokuapp.com/">Still Under Construction</a>
     <p>I am currently building a custom RoR site for my wedding. This is an evolving project as we plan the wedding itself. I look forward to adding elements like an online RSVP system, improving the proposal gallery, and so many other things. Ruby allowed me to get a site up quickly and has so many resources that I thought it would be the perfect skill to work on while building an awesome custom site for my wedding. There are a lot of great resources out there for people who cannot build their own to create a site, but I figured it would be fun and very motivating personal project to continue improving my personal skills. Stay tuned for more updates here!</p>
    </div>
   <div class="hero-unit">
      <h3>My First Tweet</h3>
	<p>A fellow Carleton grad suggested that a great practice project in Ruby is to create a website that finds a Twitter user's first tweet. I know Twitter recently released a way to do this, but I still plan on devoting a day to this soon and just getting it done. This person also referred me to Heroku which has been fantastic. 
    </div>
</div>